- hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: create new deployment for frontend 
    command: kubectl apply -f deploymentfront.yaml
  
  

  - name: create deployment for postgres
    command: kubectl apply -f deploymentpostgres.yaml
  

  - name: create new deployment for backend 
    command: kubectl apply -f deployment1.yaml  
