apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-c
  namespace: default
  labels:
    app: book-service-c
spec:
  replicas: 1
  selector:
   matchLabels:
    app: book-service-c
  template:
    metadata:
      labels:
        app: book-service-c
    spec:
      containers:
      - name: book-service-c
        image: pooja30/bookapiimage
        env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: db_name
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            
        ports:
        - containerPort: 5001	       
      imagePullSecrets:
      - name: regcred     
---
apiVersion: v1
kind: Service
metadata:
  name: book-service-c
  namespace: default
  labels:
    app: book-service-c
spec:
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  selector:
    app: book-service-c

    
