apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-c
  namespace: default
  labels:
    app: frontend-service-c
spec:
  replicas: 1
  selector:
   matchLabels:
    app: frontend-service-c
  template:
    metadata:
      labels:
        app: frontend-service-c
    spec:
      containers:
      - name: frontend-service-c
        image: pooja30/frontendapiimage

        ports:
        - containerPort: 5000	       
      imagePullSecrets:
      - name: regcred     
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-c
  namespace: default
  labels:
    app: frontend-service-c
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: frontend-service-c
  type: NodePort
    
